### ISSUE TITLE
package-release-update-pl is not passing because of daemon issue

### ISSUE THREAD

**Issue by oiricaud** [ibm-cloud-architecture/devops-demo-kabanero-pipelines#6]
Because of the following error cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Comment by hollisc** [comment]
Providing more context on this issue, Kabanero instance references a tar file that contains the Tekton Pipeline & Tasks yamls that it installs into a target cluster.  The tar file can be hosted in any type of repository and by default, it is stored with a git release.  

An alternative could be store it in a repository like Artifactory or Nexus.  The Kabanero team also provides another option to host the tar file in a docker image.  They have a script that will build a docker image with the tar file included.  

The issue here is that it is trying to use "docker" to build the image so when we execute the script inside a Tekton task, it cannot find "docker" installed in the image.  To pursue the path of creating a docker image with the tar file using Tekton, we would need to create a Tekton Task that would generate the tar and use buildah / kaniko to build an image and push it to an image registry vs using the script as is (which is meant to be run locally). 

For the tutorial (https://github.com/ibm-cloud-architecture/gse-devops/tree/master/kabanero-pipeline-managment), we will provide two flavours to host the tar file (github release and artifactory).  If there are requests for an example of hosting the tar file in a docker image, we can create a new issue to track this request.  

Closing this for now.
